# EXCEL로 만든 인공신경망을 pytorch의 Tensor 클래스을 이용하여 만들기

In [2]:
import torch
import numpy as np

필요한 함수의 정의하기

In [71]:
def ReLU_func(outputs):
    
    return np.maximum(0,outputs)

def softmax(outputs):
    # 채우기
    softmax=torch.nn.functional.softmax(outputs,dim=1)
    
    return softmax

def cross_entropy(outputs, labels):
    c=torch.nn.CrossEntropyLoss()
    loss=c(outputs,labels)
    return loss

Weight 값 설정하기

In [72]:
w_ih = torch.Tensor([
    [1,-2,3],
    [-2,5,3],
])

w_ho = torch.Tensor([
    [3,-2,4],
    [-1,2,3],
    [2,-2,-4],
])

Batch 가 3인 Input 값과 Labels 값의 입력하기

In [73]:
input = torch.Tensor([
    [2,-4],
    [0,3],
    [-6,2],
])

labels = torch.Tensor([
    [1,0,0],
    [0,1,0],
    [0,0,1],
])

L1의 활성화 함수 전의 값 구하기

In [74]:
L1 = input@w_ih
print(L1)

tensor([[ 10., -24.,  -6.],
        [ -6.,  15.,   9.],
        [-10.,  22., -12.]])


ReLU의 적용하기

In [75]:
L1 = ReLU_func(L1)
print(L1)

tensor([[10.,  0.,  0.],
        [ 0., 15.,  9.],
        [ 0., 22.,  0.]])


Output 구하기

In [76]:
outputs = L1@w_ho
print(outputs)

tensor([[ 30., -20.,  40.],
        [  3.,  12.,   9.],
        [-22.,  44.,  66.]])


Softmax의 적용

In [77]:
so = softmax(outputs)
print(so)

tensor([[4.5398e-05, 8.7561e-27, 9.9995e-01],
        [1.1754e-04, 9.5246e-01, 4.7420e-02],
        [6.0546e-39, 2.7895e-10, 1.0000e+00]])


sample별로 loss 구하기

In [86]:
a=[]
for i in range(0,3):
    loss1 = cross_entropy(so[i:i+1],labels[i:i+1]) #softmax한 텐서값을 샘플따서 각각 크로스엔트로피 취함
    loss1=loss1.item()
    a.append(loss1)


a=torch.tensor(a)
print(a)




tensor([1.5514, 0.5824, 0.5514])


최종 loss 구하기

In [87]:
loss = a.mean()
print(loss)

tensor(0.8951)


## EXCEL과 같은 답이 나오는가?

**예**

 #### 아니면 이유가 무엇인가? 


답변 하시오